"""Frontend codemap generator — extract structural index from JS/CSS.

Companion to scripts/gen_codemap.py (which only handles Python AST).
Targets the large frontend files called out as "do not full-Read" in
CLAUDE.md §5.5: radar.js (~8170 lines), tradecraft.js (~1016 lines),
radar.css (~2581 lines).

For .js: match top-level `function name(` / `async function name(` and
section-comment markers like `// ── Section ──`.
For .css: match section-comment markers like `/* ── Section ── */` and
`/* ════ Section ════ */`.

Outputs go to docs/CODEMAPS/<filename>.md alongside the Python codemaps.

Usage:
    python scripts/gen_frontend_codemap.py            # regenerate all
    python scripts/gen_frontend_codemap.py --check    # CI mode
    python scripts/gen_frontend_codemap.py radar.css  # single file
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parent.parent
CODEMAP_DIR = REPO_ROOT / "docs" / "CODEMAPS"

DEFAULT_TARGETS: tuple[str, ...] = (
    "radar.js",
    "tradecraft.js",
    "radar.css",
)

# Allow leading whitespace because radar.js wraps everything in an IIFE
# (4-space indent) but tradecraft.js does the same with its own IIFE.
_JS_FUNC_RE = re.compile(
    r"^\s*(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\("
)
_JS_SECTION_RE = re.compile(
    r"^\s*//\s*(?:──+|===+)\s*(.*?)\s*(?:──+|===+|\*/|$)"
)
_CSS_SECTION_RE = re.compile(
    r"^/\*\s*(?:──+|═+|===+)\s*(.*?)\s*(?:──+|═+|===+)?\s*\*?/?\s*$"
)


@dataclass(frozen=True)
class Marker:
    line: int
    label: str
    kind: str  # "section" or "function"


def parse_js(source: str) -> tuple[list[Marker], int]:
    markers: list[Marker] = []
    for i, line in enumerate(source.splitlines(), start=1):
        m = _JS_SECTION_RE.match(line)
        if m and m.group(1):
            label = m.group(1).strip().rstrip("─=").strip()
            if label:
                markers.append(Marker(i, label, "section"))
            continue
        m = _JS_FUNC_RE.match(line)
        if m:
            markers.append(Marker(i, m.group(1), "function"))
    return markers, len(source.splitlines())


def parse_css(source: str) -> tuple[list[Marker], int]:
    markers: list[Marker] = []
    for i, line in enumerate(source.splitlines(), start=1):
        m = _CSS_SECTION_RE.match(line.rstrip())
        if m and m.group(1):
            label = m.group(1).strip().rstrip("─═=").strip()
            if label:
                markers.append(Marker(i, label, "section"))
    return markers, len(source.splitlines())


def render_codemap(rel_path: str, markers: list[Marker], line_count: int) -> str:
    out: list[str] = []
    out.append(f"# Codemap: `{rel_path}`")
    out.append("")
    out.append("_Generated by `scripts/gen_frontend_codemap.py`. Do not hand-edit._")
    out.append("")
    out.append(f"- **Lines**: {line_count}")
    section_count = sum(1 for m in markers if m.kind == "section")
    func_count = sum(1 for m in markers if m.kind == "function")
    out.append(f"- **Sections**: {section_count}")
    if func_count:
        out.append(f"- **Top-level functions**: {func_count}")
    out.append("")

    # Group functions under their preceding section so the reader sees structure.
    sections: list[tuple[int, str, list[tuple[int, str]]]] = []
    current_section = (1, "(top of file)", [])
    sections.append(current_section)
    for m in markers:
        if m.kind == "section":
            current_section = (m.line, m.label, [])
            sections.append(current_section)
        else:
            current_section[2].append((m.line, m.label))

    out.append("## Sections")
    out.append("")
    out.append("| Lines | Section | Functions |")
    out.append("|-------|---------|-----------|")
    for start, label, funcs in sections:
        if not funcs and label == "(top of file)":
            continue
        # Compute section line range using next section start
        end = "—"
        idx = next(
            (i for i, s in enumerate(sections) if s[0] == start and s[1] == label),
            None,
        )
        if idx is not None and idx + 1 < len(sections):
            end = str(sections[idx + 1][0] - 1)
        elif idx is not None:
            end = str(line_count)
        func_str = ", ".join(f"`{name}` (L{ln})" for ln, name in funcs[:10])
        if len(funcs) > 10:
            func_str += f", … (+{len(funcs) - 10})"
        out.append(f"| L{start}–{end} | {label} | {func_str or '—'} |")
    out.append("")

    if func_count:
        out.append("## All top-level functions (alphabetical)")
        out.append("")
        out.append("| Function | Line |")
        out.append("|----------|------|")
        funcs = sorted(
            ((m.label, m.line) for m in markers if m.kind == "function"),
            key=lambda x: x[0].lower(),
        )
        for name, ln in funcs:
            out.append(f"| `{name}` | L{ln} |")
        out.append("")

    return "\n".join(out)


def codemap_path(rel_path: str) -> Path:
    return CODEMAP_DIR / f"{rel_path}.md"


def write_codemap(rel_path: str) -> tuple[Path, str]:
    src = (REPO_ROOT / rel_path).read_text(encoding="utf-8")
    if rel_path.endswith(".css"):
        markers, line_count = parse_css(src)
    else:
        markers, line_count = parse_js(src)
    body = render_codemap(rel_path, markers, line_count)
    out = codemap_path(rel_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")
    return out, body


def _hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", help="Specific files to (re)generate")
    parser.add_argument(
        "--check", action="store_true",
        help="Exit non-zero if any frontend codemap is stale",
    )
    args = parser.parse_args(argv)

    targets: Iterable[str] = tuple(args.paths) if args.paths else DEFAULT_TARGETS

    if args.check:
        stale: list[str] = []
        for rel in targets:
            src_path = REPO_ROOT / rel
            if not src_path.exists():
                continue
            src = src_path.read_text(encoding="utf-8")
            markers, line_count = (
                parse_css(src) if rel.endswith(".css") else parse_js(src)
            )
            expected = render_codemap(rel, markers, line_count)
            existing = codemap_path(rel)
            if not existing.exists() or _hash(existing.read_text()) != _hash(expected):
                stale.append(rel)
        if stale:
            print("Stale frontend codemaps. Run `python scripts/gen_frontend_codemap.py`:",
                  file=sys.stderr)
            for s in stale:
                print(f"  - {s}", file=sys.stderr)
            return 1
        print(f"OK: {len(tuple(targets))} frontend codemaps up to date.")
        return 0

    written = 0
    for rel in targets:
        if not (REPO_ROOT / rel).exists():
            print(f"SKIP (missing): {rel}", file=sys.stderr)
            continue
        out, _ = write_codemap(rel)
        written += 1
        print(f"wrote {out.relative_to(REPO_ROOT)}")
    print(f"\nGenerated {written} frontend codemaps in {CODEMAP_DIR.relative_to(REPO_ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
